apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml

helmCharts:
  - repo: https://charts.external-secrets.io/
    name: external-secrets 
    releaseName: external-secrets 
    valuesFile: values.yaml
    version: 0.9.13
