apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: eso-extsecret

spec:
 refreshInterval: "15s"
 secretStoreRef:
   name: aws-secrets-manager
   kind: SecretStore

 target:
   name: mongo-secret
   creationPolicy: Owner
   deletionPolicy: "Retain"

 data:
 - secretKey: mongo-root-username
   remoteRef:
     key: db-username
     property: mongo-root-username
     decodingStrategy: None

 - secretKey: mongo-root-password
   remoteRef:
     key: db-password
     property: mongo-root-password
     decodingStrategy: None