apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
 name: push-secret
 namespace: default
spec:
 updatePolicy: Replace
 deletionPolicy: Retain
 refreshInterval: 10s
 secretStoreRefs:
   - name: aws-parameterstore
     kind: SecretStore
 selector:
   secret:
     name: mongo-secret
 data:
   - conversionStrategy: None
     match:
       secretKey: db-username
       remoteRef:
         remoteKey: mongo-secret